// Mocks generated by Mockito 5.4.6 from annotations
// in sanad_agent/test/interfaces/compaction_queue_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:sanad_agent/capabilities/registry/tools_registry.dart' as _i3;
import 'package:sanad_agent/core/models/message.dart' as _i8;
import 'package:sanad_agent/core/models/tool_call.dart' as _i17;
import 'package:sanad_agent/engine/adapters/llm_adapter.dart' as _i2;
import 'package:sanad_agent/engine/agent_context_assembler.dart' as _i7;
import 'package:sanad_agent/engine/agent_runner.dart' as _i12;
import 'package:sanad_agent/engine/runtime/llm_route_snapshot.dart' as _i20;
import 'package:sanad_agent/engine/runtime/run_cancellation_scope.dart' as _i14;
import 'package:sanad_agent/evolution/db/session_db.dart' as _i9;
import 'package:sanad_agent/evolution/memory/file_memory_store.dart' as _i6;
import 'package:sanad_agent/evolution/models/pending_steer_record.dart' as _i15;
import 'package:sanad_agent/evolution/models/session_query.dart' as _i11;
import 'package:sanad_agent/evolution/models/session_state.dart' as _i10;
import 'package:sanad_agent/evolution/models/suspended_checkpoint.dart' as _i18;
import 'package:sanad_agent/evolution/session_manager.dart' as _i4;
import 'package:sanad_agent/evolution/title_service.dart' as _i19;
import 'package:sanad_agent/plugins/plugin_manager.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLLMAdapter_0 extends _i1.SmartFake implements _i2.LLMAdapter {
  _FakeLLMAdapter_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeToolsRegistry_1 extends _i1.SmartFake implements _i3.ToolsRegistry {
  _FakeToolsRegistry_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSessionManager_2 extends _i1.SmartFake
    implements _i4.SessionManager {
  _FakeSessionManager_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePluginManager_3 extends _i1.SmartFake implements _i5.PluginManager {
  _FakePluginManager_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileMemoryStore_4 extends _i1.SmartFake
    implements _i6.FileMemoryStore {
  _FakeFileMemoryStore_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAgentContextAssembler_5 extends _i1.SmartFake
    implements _i7.AgentContextAssembler {
  _FakeAgentContextAssembler_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessage_6 extends _i1.SmartFake implements _i8.Message {
  _FakeMessage_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSessionDB_7 extends _i1.SmartFake implements _i9.SessionDB {
  _FakeSessionDB_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSessionState_8 extends _i1.SmartFake implements _i10.SessionState {
  _FakeSessionState_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSessionQueryResult_9 extends _i1.SmartFake
    implements _i11.SessionQueryResult {
  _FakeSessionQueryResult_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AgentRunner].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgentRunner extends _i1.Mock implements _i12.AgentRunner {
  MockAgentRunner() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LLMAdapter get adapter =>
      (super.noSuchMethod(
            Invocation.getter(#adapter),
            returnValue: _FakeLLMAdapter_0(this, Invocation.getter(#adapter)),
          )
          as _i2.LLMAdapter);

  @override
  _i3.ToolsRegistry get registry =>
      (super.noSuchMethod(
            Invocation.getter(#registry),
            returnValue: _FakeToolsRegistry_1(
              this,
              Invocation.getter(#registry),
            ),
          )
          as _i3.ToolsRegistry);

  @override
  _i4.SessionManager get sessionManager =>
      (super.noSuchMethod(
            Invocation.getter(#sessionManager),
            returnValue: _FakeSessionManager_2(
              this,
              Invocation.getter(#sessionManager),
            ),
          )
          as _i4.SessionManager);

  @override
  _i5.PluginManager get pluginManager =>
      (super.noSuchMethod(
            Invocation.getter(#pluginManager),
            returnValue: _FakePluginManager_3(
              this,
              Invocation.getter(#pluginManager),
            ),
          )
          as _i5.PluginManager);

  @override
  _i6.FileMemoryStore get memoryStore =>
      (super.noSuchMethod(
            Invocation.getter(#memoryStore),
            returnValue: _FakeFileMemoryStore_4(
              this,
              Invocation.getter(#memoryStore),
            ),
          )
          as _i6.FileMemoryStore);

  @override
  String get sessionId =>
      (super.noSuchMethod(
            Invocation.getter(#sessionId),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#sessionId),
            ),
          )
          as String);

  @override
  List<_i8.Message> get history =>
      (super.noSuchMethod(
            Invocation.getter(#history),
            returnValue: <_i8.Message>[],
          )
          as List<_i8.Message>);

  @override
  bool get stopRequested =>
      (super.noSuchMethod(Invocation.getter(#stopRequested), returnValue: false)
          as bool);

  @override
  bool get providerRequestInFlight =>
      (super.noSuchMethod(
            Invocation.getter(#providerRequestInFlight),
            returnValue: false,
          )
          as bool);

  @override
  bool get canPublishRunEvents =>
      (super.noSuchMethod(
            Invocation.getter(#canPublishRunEvents),
            returnValue: false,
          )
          as bool);

  @override
  _i7.AgentContextAssembler get contextAssembler =>
      (super.noSuchMethod(
            Invocation.getter(#contextAssembler),
            returnValue: _FakeAgentContextAssembler_5(
              this,
              Invocation.getter(#contextAssembler),
            ),
          )
          as _i7.AgentContextAssembler);

  @override
  Map<String, int> get accumulatedUsage =>
      (super.noSuchMethod(
            Invocation.getter(#accumulatedUsage),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  Map<String, int> get lastUsage =>
      (super.noSuchMethod(
            Invocation.getter(#lastUsage),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  set memoryStore(_i6.FileMemoryStore? value) => super.noSuchMethod(
    Invocation.setter(#memoryStore, value),
    returnValueForMissingStub: null,
  );

  @override
  set sessionId(String? value) => super.noSuchMethod(
    Invocation.setter(#sessionId, value),
    returnValueForMissingStub: null,
  );

  @override
  set history(List<_i8.Message>? value) => super.noSuchMethod(
    Invocation.setter(#history, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentModelStepId(String? value) => super.noSuchMethod(
    Invocation.setter(#currentModelStepId, value),
    returnValueForMissingStub: null,
  );

  @override
  set activeModel(String? value) => super.noSuchMethod(
    Invocation.setter(#activeModel, value),
    returnValueForMissingStub: null,
  );

  @override
  set activeProvider(String? value) => super.noSuchMethod(
    Invocation.setter(#activeProvider, value),
    returnValueForMissingStub: null,
  );

  @override
  set accumulatedUsage(Map<String, int>? value) => super.noSuchMethod(
    Invocation.setter(#accumulatedUsage, value),
    returnValueForMissingStub: null,
  );

  @override
  set runStartTime(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#runStartTime, value),
    returnValueForMissingStub: null,
  );

  @override
  void markProviderResponseTerminalCommitted() => super.noSuchMethod(
    Invocation.method(#markProviderResponseTerminalCommitted, []),
    returnValueForMissingStub: null,
  );

  @override
  void allowManualAmbiguousToolRecovery() => super.noSuchMethod(
    Invocation.method(#allowManualAmbiguousToolRecovery, []),
    returnValueForMissingStub: null,
  );

  @override
  void beginControlledRestartDrain() => super.noSuchMethod(
    Invocation.method(#beginControlledRestartDrain, []),
    returnValueForMissingStub: null,
  );

  @override
  void cancelControlledRestartDrain() => super.noSuchMethod(
    Invocation.method(#cancelControlledRestartDrain, []),
    returnValueForMissingStub: null,
  );

  @override
  void requestStop() => super.noSuchMethod(
    Invocation.method(#requestStop, []),
    returnValueForMissingStub: null,
  );

  @override
  void attachCancellationScope(_i14.RunCancellationScope? scope) =>
      super.noSuchMethod(
        Invocation.method(#attachCancellationScope, [scope]),
        returnValueForMissingStub: null,
      );

  @override
  void detachCancellationScope(_i14.RunCancellationScope? scope) =>
      super.noSuchMethod(
        Invocation.method(#detachCancellationScope, [scope]),
        returnValueForMissingStub: null,
      );

  @override
  void beginAuthoritativeRun(
    String? runId, {
    String? workItemId,
    int? generation,
  }) => super.noSuchMethod(
    Invocation.method(
      #beginAuthoritativeRun,
      [runId],
      {#workItemId: workItemId, #generation: generation},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void configurePendingSteerLifecycle({
    required String? runId,
    required int? generation,
    void Function(_i15.PendingSteerRecord)? onChanged,
  }) => super.noSuchMethod(
    Invocation.method(#configurePendingSteerLifecycle, [], {
      #runId: runId,
      #generation: generation,
      #onChanged: onChanged,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void endAuthoritativeRun(String? runId) => super.noSuchMethod(
    Invocation.method(#endAuthoritativeRun, [runId]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<int?> getContextTokens() =>
      (super.noSuchMethod(
            Invocation.method(#getContextTokens, []),
            returnValue: _i16.Future<int?>.value(),
          )
          as _i16.Future<int?>);

  @override
  _i16.Future<Map<String, dynamic>?> getContextUsageSnapshot() =>
      (super.noSuchMethod(
            Invocation.method(#getContextUsageSnapshot, []),
            returnValue: _i16.Future<Map<String, dynamic>?>.value(),
          )
          as _i16.Future<Map<String, dynamic>?>);

  @override
  _i16.Future<void> executeToolCalls(
    List<_i17.ToolCall>? toolCalls, {
    required bool? parallel,
    _i16.Future<void> Function({
      required bool isError,
      required bool isStart,
      required String toolName,
      String? input,
      String? output,
      String? toolRunId,
    })?
    onToolEvent,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeToolCalls,
              [toolCalls],
              {#parallel: parallel, #onToolEvent: onToolEvent},
            ),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void addSystemMessage(String? content) => super.noSuchMethod(
    Invocation.method(#addSystemMessage, [content]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<_i8.Message> sendMessage(
    String? userContent, {
    String? requestId,
    String? runtimeSystemPrompt,
    String? providerId,
    String? model,
    String? thinkingMode,
    DateTime? receivedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [userContent],
              {
                #requestId: requestId,
                #runtimeSystemPrompt: runtimeSystemPrompt,
                #providerId: providerId,
                #model: model,
                #thinkingMode: thinkingMode,
                #receivedAt: receivedAt,
              },
            ),
            returnValue: _i16.Future<_i8.Message>.value(
              _FakeMessage_6(
                this,
                Invocation.method(
                  #sendMessage,
                  [userContent],
                  {
                    #requestId: requestId,
                    #runtimeSystemPrompt: runtimeSystemPrompt,
                    #providerId: providerId,
                    #model: model,
                    #thinkingMode: thinkingMode,
                    #receivedAt: receivedAt,
                  },
                ),
              ),
            ),
          )
          as _i16.Future<_i8.Message>);

  @override
  bool shouldParallelizeToolBatch(List<_i17.ToolCall>? toolCalls) =>
      (super.noSuchMethod(
            Invocation.method(#shouldParallelizeToolBatch, [toolCalls]),
            returnValue: false,
          )
          as bool);

  @override
  void setTurnRequestId(String? requestId) => super.noSuchMethod(
    Invocation.method(#setTurnRequestId, [requestId]),
    returnValueForMissingStub: null,
  );

  @override
  void updateTurnRoute({String? providerId, String? modelId}) =>
      super.noSuchMethod(
        Invocation.method(#updateTurnRoute, [], {
          #providerId: providerId,
          #modelId: modelId,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void steer(String? text) => super.noSuchMethod(
    Invocation.method(#steer, [text]),
    returnValueForMissingStub: null,
  );

  @override
  void steerEvent(String? text, {String? requestId, DateTime? receivedAt}) =>
      super.noSuchMethod(
        Invocation.method(
          #steerEvent,
          [text],
          {#requestId: requestId, #receivedAt: receivedAt},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool cancelBufferedPendingSteer(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelBufferedPendingSteer, [requestId]),
            returnValue: false,
          )
          as bool);

  @override
  void removeBufferedPendingSteers(Iterable<String>? requestIds) =>
      super.noSuchMethod(
        Invocation.method(#removeBufferedPendingSteers, [requestIds]),
        returnValueForMissingStub: null,
      );

  @override
  _i16.Stream<String> streamMessage(
    String? userContent, {
    String? requestId,
    String? runtimeSystemPrompt,
    String? providerId,
    String? model,
    String? thinkingMode,
    DateTime? receivedAt,
    _i16.Future<void> Function({
      required bool isError,
      required bool isStart,
      required String toolName,
      String? input,
      String? output,
      String? toolRunId,
    })?
    onToolEvent,
    void Function()? onSteerContinuation,
    _i16.FutureOr<void> Function(String)? onThoughtDelta,
    _i16.FutureOr<void> Function(String)? onReasoningDelta,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #streamMessage,
              [userContent],
              {
                #requestId: requestId,
                #runtimeSystemPrompt: runtimeSystemPrompt,
                #providerId: providerId,
                #model: model,
                #thinkingMode: thinkingMode,
                #receivedAt: receivedAt,
                #onToolEvent: onToolEvent,
                #onSteerContinuation: onSteerContinuation,
                #onThoughtDelta: onThoughtDelta,
                #onReasoningDelta: onReasoningDelta,
              },
            ),
            returnValue: _i16.Stream<String>.empty(),
          )
          as _i16.Stream<String>);

  @override
  _i16.Stream<String> resumeStream({
    String? requestId,
    String? runtimeSystemPrompt,
    String? providerId,
    String? model,
    String? thinkingMode,
    _i16.Future<void> Function({
      required bool isError,
      required bool isStart,
      required String toolName,
      String? input,
      String? output,
      String? toolRunId,
    })?
    onToolEvent,
    void Function()? onSteerContinuation,
    _i16.FutureOr<void> Function(String)? onThoughtDelta,
    _i16.FutureOr<void> Function(String)? onReasoningDelta,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resumeStream, [], {
              #requestId: requestId,
              #runtimeSystemPrompt: runtimeSystemPrompt,
              #providerId: providerId,
              #model: model,
              #thinkingMode: thinkingMode,
              #onToolEvent: onToolEvent,
              #onSteerContinuation: onSteerContinuation,
              #onThoughtDelta: onThoughtDelta,
              #onReasoningDelta: onReasoningDelta,
            }),
            returnValue: _i16.Stream<String>.empty(),
          )
          as _i16.Stream<String>);

  @override
  void attachMetadataToLastAssistantMessage(Map<String, dynamic>? metadata) =>
      super.noSuchMethod(
        Invocation.method(#attachMetadataToLastAssistantMessage, [metadata]),
        returnValueForMissingStub: null,
      );

  @override
  _i16.Stream<String> resumeAfterToolCall({
    required String? toolCallId,
    required String? toolName,
    required Map<String, dynamic>? arguments,
    String? runtimeSystemPrompt,
    String? forcedOutput,
    bool? forcedIsError = false,
    _i16.Future<void> Function({
      required bool isError,
      required bool isStart,
      required String toolName,
      String? input,
      String? output,
      String? toolRunId,
    })?
    onToolEvent,
    _i16.FutureOr<void> Function(String)? onThoughtDelta,
    _i16.FutureOr<void> Function(String)? onReasoningDelta,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resumeAfterToolCall, [], {
              #toolCallId: toolCallId,
              #toolName: toolName,
              #arguments: arguments,
              #runtimeSystemPrompt: runtimeSystemPrompt,
              #forcedOutput: forcedOutput,
              #forcedIsError: forcedIsError,
              #onToolEvent: onToolEvent,
              #onThoughtDelta: onThoughtDelta,
              #onReasoningDelta: onReasoningDelta,
            }),
            returnValue: _i16.Stream<String>.empty(),
          )
          as _i16.Stream<String>);
}

/// A class which mocks [SessionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionManager extends _i1.Mock implements _i4.SessionManager {
  MockSessionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.SessionDB get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeSessionDB_7(this, Invocation.getter(#db)),
          )
          as _i9.SessionDB);

  @override
  void saveInFlightSnapshot(
    String? sessionId,
    Map<String, dynamic>? snapshot,
  ) => super.noSuchMethod(
    Invocation.method(#saveInFlightSnapshot, [sessionId, snapshot]),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic>? getInFlightSnapshot(String? sessionId) =>
      (super.noSuchMethod(Invocation.method(#getInFlightSnapshot, [sessionId]))
          as Map<String, dynamic>?);

  @override
  void clearInFlightSnapshot(String? sessionId) => super.noSuchMethod(
    Invocation.method(#clearInFlightSnapshot, [sessionId]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.SessionState createSession(
    String? model, {
    String? providerId,
    String? thinkingMode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createSession,
              [model],
              {#providerId: providerId, #thinkingMode: thinkingMode},
            ),
            returnValue: _FakeSessionState_8(
              this,
              Invocation.method(
                #createSession,
                [model],
                {#providerId: providerId, #thinkingMode: thinkingMode},
              ),
            ),
          )
          as _i10.SessionState);

  @override
  _i10.SessionState? getSession(String? sessionId) =>
      (super.noSuchMethod(Invocation.method(#getSession, [sessionId]))
          as _i10.SessionState?);

  @override
  List<_i10.SessionState> getAllSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSessions, []),
            returnValue: <_i10.SessionState>[],
          )
          as List<_i10.SessionState>);

  @override
  _i11.SessionQueryResult getSessions(_i11.SessionQueryRequest? query) =>
      (super.noSuchMethod(
            Invocation.method(#getSessions, [query]),
            returnValue: _FakeSessionQueryResult_9(
              this,
              Invocation.method(#getSessions, [query]),
            ),
          )
          as _i11.SessionQueryResult);

  @override
  void updateSessionTitle(String? sessionId, String? title) =>
      super.noSuchMethod(
        Invocation.method(#updateSessionTitle, [sessionId, title]),
        returnValueForMissingStub: null,
      );

  @override
  bool updateSessionTitleIfCurrent(
    String? sessionId, {
    required String? expectedTitle,
    required String? title,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateSessionTitleIfCurrent,
              [sessionId],
              {#expectedTitle: expectedTitle, #title: title},
            ),
            returnValue: false,
          )
          as bool);

  @override
  List<_i10.SessionState> getPendingTitleSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingTitleSessions, []),
            returnValue: <_i10.SessionState>[],
          )
          as List<_i10.SessionState>);

  @override
  void deleteSession(String? sessionId) => super.noSuchMethod(
    Invocation.method(#deleteSession, [sessionId]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSessionModel(String? sessionId, String? model) =>
      super.noSuchMethod(
        Invocation.method(#updateSessionModel, [sessionId, model]),
        returnValueForMissingStub: null,
      );

  @override
  void updateSessionProviderId(String? sessionId, String? providerInstanceId) =>
      super.noSuchMethod(
        Invocation.method(#updateSessionProviderId, [
          sessionId,
          providerInstanceId,
        ]),
        returnValueForMissingStub: null,
      );

  @override
  void updateSessionModeling(
    String? sessionId, {
    String? providerId,
    String? model,
    String? thinkingMode,
  }) => super.noSuchMethod(
    Invocation.method(
      #updateSessionModeling,
      [sessionId],
      {#providerId: providerId, #model: model, #thinkingMode: thinkingMode},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void saveSessionHistory(String? sessionId, List<_i8.Message>? messages) =>
      super.noSuchMethod(
        Invocation.method(#saveSessionHistory, [sessionId, messages]),
        returnValueForMissingStub: null,
      );

  @override
  void recordCanonicalUserMessageAccepted(
    String? sessionId,
    DateTime? receivedAt,
  ) => super.noSuchMethod(
    Invocation.method(#recordCanonicalUserMessageAccepted, [
      sessionId,
      receivedAt,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  List<_i8.Message> getMessages(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [sessionId]),
            returnValue: <_i8.Message>[],
          )
          as List<_i8.Message>);

  @override
  void saveSessionMetadata(String? sessionId, Map<String, dynamic>? metadata) =>
      super.noSuchMethod(
        Invocation.method(#saveSessionMetadata, [sessionId, metadata]),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic>? getSessionMetadata(String? sessionId) =>
      (super.noSuchMethod(Invocation.method(#getSessionMetadata, [sessionId]))
          as Map<String, dynamic>?);

  @override
  void saveSuspendedCheckpoint(_i18.SuspendedCheckpoint? checkpoint) =>
      super.noSuchMethod(
        Invocation.method(#saveSuspendedCheckpoint, [checkpoint]),
        returnValueForMissingStub: null,
      );

  @override
  _i18.SuspendedCheckpoint? getSuspendedCheckpointByRequestId(
    String? requestId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSuspendedCheckpointByRequestId, [requestId]),
          )
          as _i18.SuspendedCheckpoint?);

  @override
  List<_i18.SuspendedCheckpoint> listSuspendedCheckpoints({String? status}) =>
      (super.noSuchMethod(
            Invocation.method(#listSuspendedCheckpoints, [], {#status: status}),
            returnValue: <_i18.SuspendedCheckpoint>[],
          )
          as List<_i18.SuspendedCheckpoint>);

  @override
  void updateSuspendedCheckpointStatus({
    required String? requestId,
    required String? status,
  }) => super.noSuchMethod(
    Invocation.method(#updateSuspendedCheckpointStatus, [], {
      #requestId: requestId,
      #status: status,
    }),
    returnValueForMissingStub: null,
  );

  @override
  bool claimSuspendedCheckpointDecision({
    required String? requestId,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#claimSuspendedCheckpointDecision, [], {
              #requestId: requestId,
              #status: status,
            }),
            returnValue: false,
          )
          as bool);

  @override
  void deleteSuspendedCheckpointByRequestId(String? requestId) =>
      super.noSuchMethod(
        Invocation.method(#deleteSuspendedCheckpointByRequestId, [requestId]),
        returnValueForMissingStub: null,
      );

  @override
  void deleteSuspendedCheckpointByToolCallId(String? toolCallId) =>
      super.noSuchMethod(
        Invocation.method(#deleteSuspendedCheckpointByToolCallId, [toolCallId]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TitleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTitleService extends _i1.Mock implements _i19.TitleService {
  MockTitleService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<String> generateTitle({
    required String? sessionId,
    required String? userMessage,
    required String? assistantResponse,
    String? modelOverride,
    _i20.LLMRouteSnapshot? route,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateTitle, [], {
              #sessionId: sessionId,
              #userMessage: userMessage,
              #assistantResponse: assistantResponse,
              #modelOverride: modelOverride,
              #route: route,
            }),
            returnValue: _i16.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#generateTitle, [], {
                  #sessionId: sessionId,
                  #userMessage: userMessage,
                  #assistantResponse: assistantResponse,
                  #modelOverride: modelOverride,
                  #route: route,
                }),
              ),
            ),
          )
          as _i16.Future<String>);

  @override
  _i16.Future<int> recoverPendingTitles() =>
      (super.noSuchMethod(
            Invocation.method(#recoverPendingTitles, []),
            returnValue: _i16.Future<int>.value(0),
          )
          as _i16.Future<int>);
}
