import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'src/infrastructure/client_launch_profile.dart';
import 'src/infrastructure/cloud_endpoints.dart';
import 'src/infrastructure/command_options.dart';
import 'src/infrastructure/component_journal.dart';
import 'src/infrastructure/local_gateway_credential.dart';
import 'src/infrastructure/runtime_component_control.dart';
import 'src/infrastructure/runtime_context.dart';
import 'src/infrastructure/secure_runtime_file.dart';
import 'src/infrastructure/startup_attempt.dart';
import 'src/infrastructure/startup_probe.dart';
import 'src/infrastructure/terminal_launcher.dart';
import 'src/runtime/ownership/runtime_ownership.dart';
import 'src/runtime/switch/runtime_switch.dart';

part 'src/cli/cli.dart';
part 'src/cli/cli_help.dart';
part 'src/cli/cli_parser.dart';
part 'src/cli/runtime_selection.dart';
part 'src/developer/developer_journal.dart';
part 'src/developer/developer_client.dart';
part 'src/developer/developer_agent.dart';
part 'src/developer/developer_ui_driver.dart';
part 'src/discovery/process_discovery.dart';
part 'src/discovery/agent_discovery.dart';
part 'src/discovery/instance_selection.dart';
part 'src/runtime/ownership/runtime_state.dart';
part 'src/runtime/lifecycle/runtime_wait_helpers.dart';
part 'src/runtime/lifecycle/runtime_background.dart';
part 'src/runtime/lifecycle/runtime_run.dart';
part 'src/runtime/lifecycle/runtime_status.dart';
part 'src/runtime/lifecycle/runtime_stop.dart';
part 'src/runtime/lifecycle/runtime_doctor.dart';
part 'src/runtime/lifecycle/runtime_orphan_recovery.dart';
part 'src/runtime/lifecycle/runtime_orphan_cleanup.dart';
part 'src/runtime/lifecycle/runtime_takeover.dart';
part 'src/runtime/switch/switch_admission.dart';
part 'src/runtime/switch/switch_controller.dart';
part 'src/runtime/switch/switch_process_control.dart';
part 'src/runtime/switch/switch_transaction.dart';

final int startTimestamp = DateTime.now().millisecondsSinceEpoch;
