import '../../core/provider_runtime/provider_protocol_constants.dart';
import 'provider_profile.dart';

/// Catalog of official provider **templates** (Plan 29 §7.1).
///
/// Each entry is an immutable [`ProviderProfile`](provider_profile.dart) that
/// describes a provider *kind*. User-created instances reference a template by
/// id (`templateId`) and add their own UUID, display name, credential, and
/// default model. The reserved [kCustomProviderTemplateId] template lets the
/// user build an OpenAI-compatible or Anthropic-compatible instance without a
/// hardcoded gateway name.
class ProviderRegistry {
  static const List<ProviderProfile> profiles = [
    // codex
    ProviderProfile(
      name: 'openai-codex',
      displayName: 'ChatGPT Plus Subscription',
      description: 'Access GPT models via personal ChatGPT subscription',
      defaultBaseUrl: 'https://chatgpt.com/backend-api/codex',
      envApiKeyName: 'CHATGPT_SESSION_TOKEN',
      envModelName: 'CHATGPT_MODEL',
      envBaseUrlName: 'CHATGPT_API_BASE',
      authType: 'oauth_external',
      authFlow: 'device_code',
      apiMode: 'codex_responses',
      aliases: ['codex', 'chatgpt-subscription'],
      apiKeyRequirement: ApiKeyRequirement.optional,
      authMethods: [ProviderAuthMethod.deviceCode],
      fallbackModels: [
        'gpt-5.5',
        'gpt-5.4',
        'gpt-5.4-mini',
        'gpt-5.3-codex',
        'gpt-5.3-codex-spark',
        'gpt-5.2-codex',
        'gpt-5.1-codex-max',
        'gpt-5.1-codex-mini',
        'gpt-4o',
        'o1',
      ],
    ),
    // kimi
    ProviderProfile(
      name: 'kimi',
      displayName: 'Kimi Moonshot',
      description: 'Moonshot AI API (Kimi)',
      defaultBaseUrl: 'https://api.moonshot.cn/v1',
      envApiKeyName: 'KIMI_API_KEY',
      envModelName: 'KIMI_MODEL',
      envBaseUrlName: 'KIMI_API_BASE',
      authType: 'api_key',
      apiMode: 'chat_completions',
      aliases: ['moonshot'],
      fallbackModels: ['moonshot-v1-8k', 'moonshot-v1-32k'],
      docsUrl: 'https://platform.moonshot.cn/console/api-keys',
      apiKeyRequirement: ApiKeyRequirement.required,
      authMethods: [ProviderAuthMethod.apiKey],
    ),
    // claude
    ProviderProfile(
      name: 'anthropic',
      displayName: 'Anthropic Claude',
      description: 'Official Anthropic API (Claude 3.5 Sonnet, Claude 3 Opus)',
      defaultBaseUrl: 'https://api.anthropic.com',
      envApiKeyName: 'ANTHROPIC_API_KEY',
      envModelName: 'ANTHROPIC_MODEL',
      envBaseUrlName: 'ANTHROPIC_API_BASE',
      authType: 'api_key',
      apiMode: 'anthropic_messages',
      aliases: ['claude', 'anthropic-chat'],
      fallbackModels: ['claude-3-5-sonnet-latest', 'claude-3-5-haiku-latest'],
      docsUrl: 'https://console.anthropic.com/settings/keys',
      protocol: ProviderProtocol.anthropicCompatible,
      apiKeyRequirement: ApiKeyRequirement.required,
      authMethods: [ProviderAuthMethod.apiKey],
    ),
    // nvidia
    ProviderProfile(
      name: 'nvidia',
      displayName: 'NVIDIA NIM',
      description: 'NVIDIA NIM — accelerated inference',
      defaultBaseUrl: 'https://integrate.api.nvidia.com/v1',
      envApiKeyName: 'NVIDIA_API_KEY',
      envModelName: 'NVIDIA_MODEL',
      envBaseUrlName: 'NVIDIA_API_BASE',
      authType: 'api_key',
      apiMode: 'chat_completions',
      aliases: ['nvidia-nim'],
      docsUrl: 'https://build.nvidia.com',
      apiKeyRequirement: ApiKeyRequirement.required,
      authMethods: [ProviderAuthMethod.apiKey],
      fallbackModels: [
        'z-ai/glm-5.1',
        'moonshotai/kimi-k2.6',
        'minimaxai/minimax-m3',
        'nex-agi/nex-n2-pro:free',
        'nvidia/nemotron-3-ultra-550b-a55b',
        'qwen/qwen3.7-max',
        'stepfun-ai/step-3.7-flash',
        'deepseek-ai/deepseek-v4-flash',
        'minimaxai/minimax-m2.7',
        'google/gemma-4-31b-it',
      ],
    ),
    // openai
    ProviderProfile(
      name: 'openai',
      displayName: 'OpenAI',
      description: 'Official OpenAI API (GPT-4o, o1, o3-mini)',
      defaultBaseUrl: 'https://api.openai.com/v1',
      envApiKeyName: 'OPENAI_API_KEY',
      envModelName: 'OPENAI_MODEL',
      envBaseUrlName: 'OPENAI_API_BASE',
      authType: 'api_key',
      apiMode: 'chat_completions',
      thinkingPolicyId: 'openai_chat_effort',
      aliases: ['gpt', 'openai-chat'],
      fallbackModels: ['gpt-4o', 'gpt-4o-mini', 'o1-mini'],
      docsUrl: 'https://platform.openai.com/api-keys',
      apiKeyRequirement: ApiKeyRequirement.required,
      authMethods: [ProviderAuthMethod.apiKey],
    ),
    // openrouter
    ProviderProfile(
      name: 'openrouter',
      displayName: 'OpenRouter',
      description: 'Unified gateway to many models',
      defaultBaseUrl: 'https://openrouter.ai/api/v1',
      envApiKeyName: 'OPENROUTER_API_KEY',
      envModelName: 'OPENROUTER_MODEL',
      envBaseUrlName: 'OPENROUTER_API_BASE',
      authType: 'api_key',
      apiMode: 'chat_completions',
      thinkingPolicyId: 'aggregator_upstream',
      aliases: ['open-router'],
      defaultHeaders: {'X-Title': 'Sanad'},
      docsUrl: 'https://openrouter.ai/keys',
      apiKeyRequirement: ApiKeyRequirement.required,
      authMethods: [ProviderAuthMethod.apiKey],
      fallbackModels: [
        'z-ai/glm-5.2',
        'moonshotai/kimi-k2.7-code',
        'minimax/minimax-m3',
        'nex-agi/nex-n2-pro:free',
        'nvidia/nemotron-3-ultra-550b-a55b',
        'qwen/qwen3.7-max',
        'anthropic/claude-3.5-sonnet',
        'google/gemini-2.5-flash',
        'deepseek/deepseek-chat',
        'deepseek/deepseek-reasoner',
        'openai/gpt-4o',
        'openai/gpt-4o-mini',
        'openai/gpt-5.5',
        'anthropic/claude-opus-4.7',
        'anthropic/claude-sonnet-latest',
        'google/gemini-3.1-pro-preview',
        'google/gemini-pro-latest',
        'deepseek/deepseek-v4-pro',
        'moonshotai/kimi-k2.6',
        'google/gemma-4-31b-it',
        'meta-llama/llama-4-maverick',
        'mistralai/mistral-large-2512',
        'qwen/qwen3-next-80b-a3b-instruct',
        'cohere/command-r-plus-08-2024',
        'mistralai/mixtral-8x22b-instruct',
      ],
    ),
    // google gemini
    ProviderProfile(
      name: 'gemini',
      displayName: 'Google Gemini',
      description:
          'Official Google Gemini Developer API (via OpenAI compatibility layer)',
      defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
      envApiKeyName: 'GEMINI_API_KEY',
      envModelName: 'GEMINI_MODEL',
      envBaseUrlName: 'GEMINI_API_BASE',
      authType: 'api_key',
      apiMode: 'chat_completions',
      thinkingPolicyId: 'google_thinking',
      aliases: ['google', 'google-gemini'],
      fallbackModels: ['gemini-1.5-pro', 'gemini-1.5-flash'],
      docsUrl: 'https://aistudio.google.com/app/apikey',
      apiKeyRequirement: ApiKeyRequirement.required,
      authMethods: [ProviderAuthMethod.apiKey],
    ),
    // deepseek
    ProviderProfile(
      name: 'deepseek',
      displayName: 'DeepSeek',
      description: 'Official DeepSeek API (DeepSeek-V3, DeepSeek-R1)',
      defaultBaseUrl: 'https://api.deepseek.com',
      envApiKeyName: 'DEEPSEEK_API_KEY',
      envModelName: 'DEEPSEEK_MODEL',
      envBaseUrlName: 'DEEPSEEK_API_BASE',
      authType: 'api_key',
      apiMode: 'chat_completions',
      thinkingPolicyId: 'deepseek_thinking',
      aliases: ['deep-seek'],
      fallbackModels: ['deepseek-chat', 'deepseek-reasoner'],
      docsUrl: 'https://platform.deepseek.com/api_keys',
      apiKeyRequirement: ApiKeyRequirement.required,
      authMethods: [ProviderAuthMethod.apiKey],
    ),
    // opencode-go
    ProviderProfile(
      name: 'opencode-go',
      displayName: 'OpenCode Go',
      description: '\$10/month subscription for open coding models',
      defaultBaseUrl: 'https://opencode.ai/zen/go/v1',
      envApiKeyName: 'OPENCODE_GO_API_KEY',
      envModelName: 'OPENCODE_GO_MODEL',
      envBaseUrlName: 'OPENCODE_GO_BASE_URL',
      authType: 'api_key',
      apiMode: 'chat_completions',
      aliases: ['opencode_go', 'go', 'opencode-go-sub'],
      fallbackModels: [
        'kimi-k2.7-code',
        'kimi-k2.6',
        'kimi-k2.5',
        'glm-5.2',
        'glm-5.1',
        'glm-5',
        'mimo-v2.5-pro',
        'mimo-v2.5',
        'mimo-v2-pro',
        'mimo-v2-omni',
        'minimax-m3',
        'minimax-m2.7',
        'minimax-m2.5',
        'deepseek-v4-pro',
        'deepseek-v4-flash',
        'qwen3.7-max',
        'qwen3.7-plus',
        'qwen3.6-plus',
        'qwen3.5-plus',
      ],
      docsUrl: 'https://opencode.ai/auth',
      apiKeyRequirement: ApiKeyRequirement.required,
      authMethods: [ProviderAuthMethod.apiKey],
    ),
    // ollama
    ProviderProfile(
      name: 'ollama',
      displayName: 'Ollama (Local)',
      description: 'Local models run via Ollama',
      defaultBaseUrl: 'http://localhost:11434',
      envModelName: 'OLLAMA_MODEL',
      envBaseUrlName: 'OLLAMA_BASE_URL',
      authType: 'api_key',
      authFlow: 'custom_endpoint',
      apiMode: 'ollama',
      aliases: ['local', 'ollama-local', 'custom-ollama'],
      fallbackModels: ['gemma4:e2b', 'llama3:latest'],
      supportsModelFetch: true,
      apiKeyRequirement: ApiKeyRequirement.optional,
      authMethods: [ProviderAuthMethod.apiKey],
    ),
    // lm-studio
    ProviderProfile(
      name: 'lm-studio',
      displayName: 'LM Studio (Local)',
      description: 'Local models run via LM Studio',
      defaultBaseUrl: 'http://localhost:1234/v1',
      envModelName: 'LM_STUDIO_MODEL',
      envBaseUrlName: 'LM_STUDIO_BASE_URL',
      authType: 'api_key',
      authFlow: 'custom_endpoint',
      apiMode: 'chat_completions',
      aliases: ['lmstudio', 'lm-studio-local'],
      fallbackModels: ['meta-llama-3-8b-instruct'],
      supportsModelFetch: true,
      apiKeyRequirement: ApiKeyRequirement.optional,
      authMethods: [ProviderAuthMethod.apiKey],
    ),
    // llama.cpp
    ProviderProfile(
      name: 'llama-cpp',
      displayName: 'llama.cpp (Local)',
      description: 'Local models run via llama.cpp server',
      defaultBaseUrl: 'http://localhost:8080/v1',
      envModelName: 'LLAMA_CPP_MODEL',
      envBaseUrlName: 'LLAMA_CPP_BASE_URL',
      authType: 'api_key',
      authFlow: 'custom_endpoint',
      apiMode: 'chat_completions',
      aliases: ['llamacpp', 'llama.cpp'],
      fallbackModels: ['custom-model'],
      supportsModelFetch: true,
      apiKeyRequirement: ApiKeyRequirement.optional,
      authMethods: [ProviderAuthMethod.apiKey],
    ),
    // xai
    ProviderProfile(
      name: 'xai',
      displayName: 'xAI Grok',
      description: 'Official xAI Grok API',
      defaultBaseUrl: 'https://api.x.ai/v1',
      envApiKeyName: 'XAI_API_KEY',
      envModelName: 'XAI_MODEL',
      envBaseUrlName: 'XAI_API_BASE',
      authType: 'api_key',
      apiMode: 'chat_completions',
      aliases: ['grok', 'x-ai', 'x.ai'],
      fallbackModels: ['grok-2-1212', 'grok-beta'],
      docsUrl: 'https://console.x.ai',
      apiKeyRequirement: ApiKeyRequirement.required,
      authMethods: [ProviderAuthMethod.apiKey],
    ),
    // zai
    ProviderProfile(
      name: 'zai',
      displayName: 'Z.AI',
      description: 'Z.AI / GLM API',
      defaultBaseUrl: 'https://api.z.ai/api/paas/v4',
      envApiKeyName: 'ZAI_API_KEY',
      envModelName: 'ZAI_MODEL',
      envBaseUrlName: 'ZAI_API_BASE',
      authType: 'api_key',
      apiMode: 'chat_completions',
      aliases: ['glm', 'z-ai', 'z.ai', 'zhipu'],
      fallbackModels: [
        'glm-4-plus',
        'glm-4-flash',
        'glm-4-9b',
        'glm-4.5-air',
        'glm-4.7-flash',
      ],
      docsUrl: 'https://open.bigmodel.cn/',
      apiKeyRequirement: ApiKeyRequirement.required,
      authMethods: [ProviderAuthMethod.apiKey],
    ),
    // zai-coding
    ProviderProfile(
      name: 'zai-coding',
      displayName: 'Z.AI Coding Plan',
      description: 'Z.AI Coding Plan API',
      defaultBaseUrl: 'https://api.z.ai/api/coding/paas/v4',
      envApiKeyName: 'ZAI_CODING_API_KEY',
      envModelName: 'ZAI_CODING_MODEL',
      envBaseUrlName: 'ZAI_CODING_API_BASE',
      authType: 'api_key',
      apiMode: 'chat_completions',
      aliases: ['zai-coding', 'glm-coding-plan', 'zhipu-coding-plan'],
      fallbackModels: ['glm-4.7', 'glm-5.1', 'glm-4.5-air', 'glm-5-turbo'],
      docsUrl: 'https://docs.z.ai/devpack/overview',
      apiKeyRequirement: ApiKeyRequirement.required,
      authMethods: [ProviderAuthMethod.apiKey],
    ),
    // custom
    ProviderProfile(
      name: kCustomProviderTemplateId,
      displayName: 'Custom Provider',
      description:
          'Any OpenAI-compatible or Anthropic-compatible endpoint you configure manually',
      authType: 'api_key',
      authFlow: 'custom_endpoint',
      apiMode: 'chat_completions',
      aliases: ['custom-provider', 'generic'],
      supportsModelFetch: true,
      apiKeyRequirement: ApiKeyRequirement.optional,
      authMethods: [ProviderAuthMethod.apiKey],
    ),
  ];

  static ProviderProfile? findByNameOrAlias(String identifier) {
    final lower = identifier.toLowerCase();
    for (var profile in profiles) {
      if (profile.name == lower || profile.aliases.contains(lower)) {
        return profile;
      }
    }
    return null;
  }
}
