// This file is automatically generated. Do not edit manually.
const String defaultEnvContent =
    r'''# ==============================================================================
# Sanad Agent - Environment Configuration Example
# ==============================================================================

# LLM providers, instances, credentials, and model selection are configured
# through the Sanad provider settings store. They do not belong in this file.

# --- Web Search Settings ---
# Preferred search provider. Choices: serper, ddg (DuckDuckGo scraper).
# DuckDuckGo scraper is the keyless fallback and is used if serper is unconfigured.
WEB_SEARCH_PROVIDER=ddg
# API Key for Google Serper API (Optional, Serper has a free tier)
SERPER_API_KEY=

# --- Runtime Feature Settings ---
# Allows the agent to recover from eligible provider failures by switching to
# another configured instance that has per-instance failover enabled.
PROVIDER_AUTO_FAILOVER=true
# Enables OS UI automation tools. The operating system may require additional
# accessibility and screen-recording permission grants.
COMPUTER_USE=false

# --- Sanad Agent Gateway & Local Server Settings ---
# The EastStar AI cloud gateway and portal have safe built-in defaults.
# Internal deployments can still override GATEWAY_URL and PORTAL_URL in their
# process environment without placing those values in the public template.
ENABLE_GATEWAY=true

ENABLE_LOCAL_GATEWAY=true
LOCAL_GATEWAY_PORT=58085
# Network interface host to bind the local gateway server to (e.g. 127.0.0.1 for local only, 0.0.0.0 to allow access from local network)
LOCAL_GATEWAY_HOST=127.0.0.1

# --- Logging (Optional) ---
# LOG_LEVEL options: ALL, FINE, INFO, WARNING, SEVERE
LOG_LEVEL=INFO
LOG_COLOR=true
LOG_MAX_LENGTH=500

# --- LLM Request Dumping (Optional Debugging) ---
# DUMP_REQUESTS=true captures prompt payloads and error logs into separate session files.
# DUMP_REQUESTS_STDOUT=true prints prompt payloads to standard output (stdout).
DUMP_REQUESTS=false
DUMP_REQUESTS_STDOUT=false
''';
